### PR TITLE
Address various typing issues

### PR DESCRIPTION
**Pull request by widerschein**
Address issues from static type checker.

### CODE REVIEW

**Comment by PanekOndrej** [comment]
- that `__eq__` method should be also modified in "Parameter", "Criterion", "Response" and "DesignVariable" class (and child classes of these) to maintain comparison methods consistent
  -  `isinstace()` will be true also for parent classes
`file1: File` 
`file2: RegisteredFile`
first case: `file2 == file1 -> isinstance(file1, RegisterFile)` -> False
second case: `file1 == file2 -> isinstance(file2, File)` -> True (but incomplete check, only `File` properties are compared
- `tuple` is used in whole package as a return type, similar situation with obtaining parameters, criteria, responses, nodes ...

**Comment by widerschein** [comment]
Ah, thanks for the hint :smiley:  I'll go back to using type().

Just to to make sure: the desired behavior is that class is always unequal subclass, even if the base properties all match, right?


> * that `__eq__` method should be also modified in `Parameter`, `Criterion`, `Response` and `DesignVariable` class (and child classes of these) to maintain comparison methods consistent
>  * `tuple` is used in whole package as a return type, similar situation with obtaining parameters, criteria, responses, nodes ...

Yes, it's still a draft PR. Going from tuple to list or iterable is also an API change, so we should take our time with this PR.

**Comment by widerschein** [comment]
On second thought, the tuple/list stuff should be handled in a separate issue.

**Comment by PanekOndrej** [comment]
> 
> Just to to make sure: the desired behavior is that class is always unequal subclass, even if the base properties all match, right?
> 

 - Yes, this is what I would expect as a user (that order of compared items doesn't matter).

As for `Tuple` as a return type - the idea behind this is that it's immutable so user can't directly add/remove new items, which may lead to problems if working further with the return value, and it should also force the user to look for some method that adds file/node/parameter..., instead of appending this to the return value and expecting some changes in optiSLang project.

But the decision is up to you, I just wanted to clarify original intentions with this. We can definitely change variable length items return type to `list`.

**Comment by widerschein** [comment]
Thanks for explaining the intention behind this. It makes perfect sense so I am fine with tuple.

**Comment by widerschein** [comment]
Looking through `feat/proxy-structure` it seems like a lot of files will be moved around. Might be better not to continue with the typing issues on `main` for now.

**Comment by PanekOndrej** [comment]
> Looking through `feat/proxy-structure` it seems like a lot of files will be moved around. Might be better not to continue with the typing issues on `main` for now.

- Yes, but these changes are mostly related to the classes that are connected to the server. I sent you an email with UML (it's not completely up to date, some functions were moved).

**Review by rfahlberg — APPROVED** [review]

**Pull request merged**
