### PR TITLE
Resolve typing issues in example-fetcher

### PR DESCRIPTION
**Pull request by widerschein**
- Resolve typing issues
- Enforce types for example dicts
- Respect potential `None` values

### CODE REVIEW

**Comment by PanekOndrej** [comment]
Those `Optional` changes should be added to the docstring as well to make typing or return values consistent, or? @widerschein

**Comment by widerschein** [comment]
> Those `Optional` changes should be added to the docstring as well to make typing or return values consistent, or? @widerschein

Addressed

**Comment by PanekOndrej** [comment]
> > Those `Optional` changes should be added to the docstring as well to make typing or return values consistent, or? @widerschein
> 
> Addressed

Btw this was also the case in previous PR concerning typing issues, the docstrings remained unchanged (I overlooked it in my code review), but I'm already working on this and will fix it together with feat/implement-new-queries-commands branch.

**Comment by widerschein** [comment]
Ah, thanks. I forgot these. Well, didn't get wronger at least.

Might even be worthwhile to consider [omitting types in the docstring ](https://dev.docs.pyansys.com/doc-style/docstrings.html#type-hints)altogether.

**Comment by PanekOndrej** [comment]
I like it, we wouldn't have to maintain types in 2 places. We could try to implement this in feat/proxy-structure branch (or after its merged into main). I don't think it's worth implementing right now, since there will be many changes and implementation of this will require modifying whole module.

**Comment by PanekOndrej** [comment]
@widerschein - add `from __future__ import annotations`  to make `TYPE_CHECKING`  work as is. You have to use `''` with these type hints otherwise (`'ExampleFiles'`).

**Comment by widerschein** [comment]
Thx @PanekOndrej. Already removed the TYPE_CHECKING check.

**Review by PanekOndrej — APPROVED** [review]

**Review by rfahlberg — APPROVED** [review]

**Pull request merged**
